name: TestGo
on: push
jobs:
  build:
    name: Build
#   runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        run: go build ./go/download_zip/

      - name: List1
        run: ls ./
        
      - name: Test
        run: go test -v ./go/download_zip/

      - name: List2
        run: ls ./
